name: CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Print config file path
        run: echo $APP_CONFIG
        
  deploy-to-dev:
    runs-on: ubuntu-latest
    #environment: dev
    env:
      APP_CONFIG: dev.txt
      PROJECT_NAME: "braavos"
      PROJECT_STAGE: "dev"
      STACK_NAME: "WireInfraStack"
    steps:    
      - name: Print env conf
        run: |
          echo env.$APP_CONFIG
          #cat env.$APP_CONFIG
          
      - name: Print environment conf
        run: |
          echo "${{ secrets.CONFIG }}"
          #cat "${{ secrets.CONFIG }}"
          
      - name: Upload file to s3 bucket and update the lambda
          S3BucketName = "$PROJECT_NAME""$PROJECT_STAGE"-"$STACK_NAME"-lambda-repo
          echo $S3BucketName
          
      
        
